spring.application.name=maxinsurance-config-client
spring.config.import=configserver:http://localhost:8888
server.port=8084


#To enable the /actuator/refresh endpoint in your
#Spring Boot application so you can refresh configuration properties at runtime,
management.endpoints.web.exposure.include=refresh
